export { apiClient } from './client'
export { whatsappApi } from './whatsapp'
export { messagesApi } from './messages'
export { leadsApi } from './leads'
export { kanbanApi } from './kanban'
export { followupsApi } from './followups'
export { dashboardApi } from './dashboard'
export type { WhatsAppInstance, QRCodeResponse, InstanceStatusResponse } from './whatsapp'
export type { Message, SendMessageDTO, MessagesResponse } from './messages'
export type { Lead, LeadFilters, PaginatedLeads, CreateLeadDTO, UpdateLeadDTO, ImportResult } from './leads'
export type { KanbanStage, KanbanLead, KanbanColumn, CreateStageDTO, UpdateStageDTO } from './kanban'
export type { Followup, FollowupFilters, PaginatedFollowups, CreateFollowupDTO, UpdateFollowupDTO, FollowupCounts } from './followups'
export type { DashboardStats, ActivityItem, ActivityResponse } from './dashboard'
